/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "adc.h"
#include "switch.h"
#include "i2c_lcd.h"
#include "i2c.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*1. On switch press, read ADC (LDR) input and display on I2C LCD.*/

int main(void)
{
	char str[32];
	uint16_t val;
	SystemInit();
	LcdInit();
	ADC_Init();
	SwitchInit(SWITCH);
	LcdPuts(LCD_LINE1, "ADC Value");
	//UartInit(BAUD_9600);
	//UartPuts("DESD ADC Demo...\r\n");
	while(1)
	{
		while(exti0_flag == 0)
				;
		 val = ADC_GetValue();
		 sprintf(str, "%d", val);
		 LcdPuts(LCD_LINE2, str);
		 exti0_flag = 0;
		 DelayMs(1000);

	}
	return 0;
}

/*
 int ret, count;
	char str[32];
	SystemInit();
	ret = LcdInit();
	if(ret) {
		LcdPuts(LCD_LINE1, "!DESD @ SUNBEAM!");
		for(count = 1; count < 100; count++) {
			sprintf(str, "GOD BLESS YOU %d", count);
			LcdPuts(LCD_LINE2, str);
			DelayMs(500);
		}
	}
*/

